version: "3.7"
services:

  ring-mtr:
    build: .
    image: ghcr.io/enix/ring-mtr
    env_file: ring-mtr.env
    environment:
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
    volumes:
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
